### ISSUE TITLE
Get inspired ...

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/smart-array-filter#1]
https://help.github.com/articles/search-syntax/

Basically they do exactly the same but extend it to >, <, >=, <=, .. , ...

**Comment by targos** [comment]
if we want to go there, we need to change the behavior for numbers. currently they are treated as strings

**Comment by targos** [comment]
I have nothing against that btw

**Comment by lpatiny** [comment]
Because today even for a number the "part of" applies I guess.
Maybe indeed if it is a number it should not be contain but "equal" and if there is the sign >, <,. ... the first condition would be to check if it is a number.

**Comment by lpatiny** [comment]
In fact it looks like really a nice library that would be impressive to use in some application. Query like

green 1992..1998

Would look for any text field that contains green and a number between 1992 and 1998
