### ISSUE TITLE
correctly escape the reserved characters

### ISSUE THREAD

**Issue by David-Turbert** [cheminfo-js/smart-array-filter#7]
In this [exemple](https://www.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/smartArray/view.json&dataURL=../testcase/data/smartArray/data.json) the hazard:"T+" search does not work. 

.^$*+?()[{\| are the reserved characters.

I think this is the same problem than #6

**Comment by targos** [comment]
it's not the same problem

**Comment by targos** [comment]
ref: https://github.com/benjamingr/RegExp.escape
